### ISSUE TITLE
Please add docker-compose and gradle download

### ISSUE THREAD

**Issue by franciscof5** [oldjazjef/docker-ionic-build-android#1]
The line 

RUN apt -y install gradle

returns unable to locate package, but I cant add 
RUN add-apt-repository ppa:cwchien/gradle

either

RUN apt-get install -y software-properties-common

Besides openjdk docker is no longer supported

**Comment by oldjazjef** [comment]
Hey i updated the whole docker image to be used with yum.
Gradle will automatically be installed with the ./gradlew assemble... command.
